# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
[graph]
targets = [
	{ triple = "x86_64-unknown-linux-gnu" },
	{ triple = "aarch64-unknown-linux-gnu" },
	{ triple = "x86_64-unknown-linux-musl" },
	{ triple = "aarch64-apple-darwin" },
	{ triple = "x86_64-apple-darwin" },
	{ triple = "x86_64-pc-windows-msvc" },
]

[advisories]
yanked = "deny"

[bans]
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93

# the good licenses
allow = [
	"MIT",
	"Apache-2.0",
	"Apache-2.0 WITH LLVM-exception",
	"Zlib",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"ISC",
	"MPL-2.0",
	"CC0-1.0",
	"OFL-1.1",
]

# semi global exceptions (the stuff I always run into)
# add local exceptions to deny.exceptions.toml
exceptions = [{ allow = ["Unicode-DFS-2016"], crate = "unicode-ident" }]
