name: actionlint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  actionlint:
    uses: chrisliebaer/workflows/.github/workflows/actionlint.yml@dc631a02f4ab7e576765fb1e770bfad81985c446
