name: Build Docker image
on:
  push:
    branches:
      - master
jobs:
  docker:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: "ghcr.io/${{ github.repository }}"
          tag-sha: true
          tag-custom: latest
      - name: "Setup Docker Buildx"
        uses: "docker/setup-buildx-action@v1"
      - name: "Login to ghcr.io"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push to registry"
        uses: "docker/build-push-action@v2"
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
