name: clippy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clippy:
    uses: chrisliebaer/.github/.github/workflows/clippy.yml@dc631a02f4ab7e576765fb1e770bfad81985c446
