name: rustfmt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rustfmt:
    uses: chrisliebaer/.github/.github/workflows/rustfmt.yml@dc631a02f4ab7e576765fb1e770bfad81985c446
